name: Monitor Scraping

on:
  schedule:
    - cron: "0 */4 * * *" # Uruchomienie co 4 godziny
  workflow_dispatch: # Pozwala na ręczne uruchomienie workflow

jobs:
  run_scraping:
    runs-on: ubuntu-latest # Używa najnowszego systemu Ubuntu
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Określa wersję Node.js

      - name: Install dependencies
        run: npm install # Instalacja zależności

      - name: Run the script
        run: node your_script.js # Uruchomienie Twojego skryptu
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
