name: Scrape prices and send email

on:
  schedule:
    - cron: "0 */4 * * *" # uruchamia skrypt co 4 godziny
  workflow_dispatch: # umożliwia ręczne uruchomienie

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Zaktualizowano do wersji 16 (lub 14)

      - name: Install dependencies
        run: npm install

      - name: Run price scraper script
        run: node script.js # Upewnij się, że nazwa pliku jest poprawna
